#!/bin/bash

export DEBUG_PROFILE=success!
export DEVDB_HOST=devdb.db.cj.com
export DEVDB_PORT=1521
export DEVDB_SID=devdb
export BUILD_USER=spud
export APPS_HOME=/home/mschober/apps
export ARDUINO_HOME=$APPS_HOME/arduino
export TITANIUM_HOME=$APPS_HOME/titanium
export HADOOP_HOME=$APPS_HOME/hadoop
export PLAY_HOME=$APPS_HOME/play
export SCALA_HOME=$APPS_HOME/scala
export PIG_HOME=$APPS_HOME/pig
export IDEA_HOME=$APPS_HOME/idea
export SQLDEVELOPER=$APPS_HOME/sqldeveloper/sqldeveloper
export HBASE_HOME=$APPS_HOME/hbase
export ZOOKEEPER_HOME=$HBASE_HOME
export SQOOP_HOME=$APPS_HOME/sqoop
export MONGO=$APPS_HOME/mongo
export MAVEN_HOME=$APPS_HOME/maven
export LC_COLLATE=POSIX
export CJP4WORKSPACE=$HOME/cj/perforce
export GIT_PERSONAL=$HOME/cj/personal/mschober/main
export GOCK_HOME=$HOME/bin/ck.sh
export MVN_RESULTS=$HOME/cj/mvn-results
export STICKIES=$HOME/cj/stickies
export CURRENT_SCHEMA=$HOME/current-schema
export GRADLE_HOME=$APPS_HOME/gradle
export EVERPAD_HOME=$APPS_HOME/everpad
export ELASTIC_SEARCH_HOME=$APPS_HOME/elasticsearch
export SOFTWARE_FOLDER=/home/mschober/cj/perforce/software

PATH=$HOME/sqllib/bin:$PATH
PATH=$SOFTWARE_FOLDER/bin:$PATH
PATH=$APPS_HOME/projector/bin:$PATH
PATH=$SOFTWARE_FOLDER/shared-scripts/bin:$PATH
PATH=$APPS_HOME/bin:$PATH
PATH=$HADOOP_HOME/bin:$PATH
PATH=$PIG_HOME/bin:$PATH
PATH=$IDEA_HOME/bin:$PATH
PATH=$HBASE_HOME/bin:$PATH
PATH=$SQOOP_HOME/bin:$PATH
PATH=$ARDUINO_HOME:$PATH
PATH=$SCALA_HOME/bin:$PATH
PATH=$PLAY_HOME:$PATH
PATH=$TITANIUM_HOME:$PATH
PATH=$SOFTWARE_FOLDER/cdh/cdh3u2/bin:$PATH
PATH=$HOME/bin:$PATH
PATH=$HOME/bin/filters:$PATH
PATH=$GRADLE_HOME/bin:$PATH
PATH=$EVERPAD_HOME/bin:$PATH
PATH=$ELASTIC_SEARCH_HOME/bin:$PATH
