#!/bin/bash

SOFTWARE=~/cj/perforce/software
APP_PATH=$SOFTWARE/bin/mongo

chooseCollection(){
    if [[ -n $2 ]]; then
        DATABASE=$2
    else
        DATABASE=fastbi-migrated
    fi
}

startMongo(){
    if [[ $1 == "local" ]]; then
        $APP_PATH localhost/$DATABASE
    elif [[ $1 == "dev" ]]; then
        $APP_PATH busprod102.wl.cj.com:27003/$DATABASE
    elif [[ $1 == "old" ]]; then
        $APP_PATH build107.wl.cj.com/$DATABASE
    fi
}


chooseCollection $@
startMongo $@
