#!/bin/bash

SOFTWARE=~/cj/perforce/software
APP_PATH=$SOFTWARE/bin/mongo

chooseCollection(){
    
    if [[ -n $2 ]]; then
        COLLECTION=$2
    else
        COLLECTION=fastbi-migrated
    fi
}

startMongo(){
    if [[ $1 == "local" ]]; then
        $APP_PATH localhost/$COLLECTION
    elif [[ $1 == "dev" ]]; then
    echo collection is: $COLLECTION
        $APP_PATH busprod102.wl.cj.com:27003/$COLLECTION
    else
        $APP_PATH build107.wl.cj.com/$COLLECTION
    fi
}


chooseCollection
startMongo
