#!/bin/bash

echo "
mbfs -o username=vivek,password=D1W4x9sw //ntserver/download /mnt/ntserver
sudo mkdir /mnt/ntserver
mount -t smbfs -o username=mschober  \\blsqldmordv01\radprod\r_dat
mount -t smbfs -o username=mschober  //blsqldmordv01/radprod/r_dat /mnt/ntserver
mount -t smbfs  //blsqldmordv01/radprod/r_dat /mnt/ntserver
mount -t smbfs  -o //blsqldmordv01/radprod/r_dat /mnt/ntserver
mount -t smbfs  -o username //blsqldmordv01/radprod/r_dat /mnt/ntserver
sudo mount -t smbfs -o username=mschober //blsqldmordv01/radprod/r_dat /mnt/ntserver
mount -t smbfs -o username=mschober //blsqldmordv01/radprod/r_dat /mnt/ntserver
mount -t smbfs -o username=mschober //blsqldmordv01/radprod /mnt/ntserver
mount -t smbfs //mschober@blsqldmordv01/radprod/r_dat /mnt/ntserver
sudo mount -t smbfs //mschober@blsqldmordv01/radprod/r_dat /mnt/ntserver
ls /mnt/ntserver 
sudo -i
ls
history
"
