#!/bin/bash

SCRIPTNAME=$1
BUCKET=$2
COMMAND=$3

BINPATH=$HOME/bin
SCRIPTPATH=$BINPATH/$BUCKET
FULLPATH=$SCRIPTPATH/$SCRIPTNAME
LINKPATH=$BINPATH/$SCRIPTNAME

mkdir -v $SCRIPTPATH

if [[ -f $FULLPATH ]]; then
  echo $FULLPATH exists, exiting
  exit 1
fi

echo '#!/bin/bash' > $FULLPATH
echo "$COMMAND" >> $FULLPATH
chmod +x $FULLPATH
ln -s $FULLPATH $LINKPATH

echo "Created new script: $(file -h $LINKPATH)"
echo "With content: "
cat $LINKPATH
