#!/bin/bash

set -o nounset
NO_BUCKET_ERROR="No bucket choosen"

SCRIPTNAME=$1
BUCKET=${2:-""} #default to BINPATH
COMMAND=${3:-""}

#[[ $BUCKET = $NO_BUCKET_ERROR ]] && echo -e "Script: $SCRIPTNAME\n$NO_BUCKET_ERROR\nExiting" && exit 1

BINPATH=$HOME/bin
MANPATH=$HOME/man/man8
SCRIPTPATH=$BINPATH/$BUCKET
FULLPATH=$SCRIPTPATH/$SCRIPTNAME
LINKPATH=$BINPATH/$SCRIPTNAME

mkdir -v $SCRIPTPATH

if [[ -f $FULLPATH ]]; then
  echo $FULLPATH exists, exiting
  exit 1
fi

echo '#!/bin/bash' > $FULLPATH
echo 'set -o nounset' >> $FULLPATH
chmod +x $FULLPATH
ln -s $FULLPATH $LINKPATH

if [[ -z $COMMAND ]]; then
  edit $SCRIPTNAME
else
  echo "$COMMAND" >> $FULLPATH
fi

echo "Created new script, temporarily linking to: $(file -h $LINKPATH)"
echo "With content: "
cat $FULLPATH

MAN_TEMPLATE=$HOME/man/man_template.txt
sed "s/nuseradd/$SCRIPTNAME/g" $MAN_TEMPLATE > $MANPATH/$SCRIPTNAME.1
gzip $MANPATH/$SCRIPTNAME.1

