#!/usr/bin/perl -w
use strict;

my $perforce_checkout = $ENV{CJP4WORKSPACE};
my $str = `p4 opened`;
for my $line (split(/\n/, $str)) {
    $line =~ s/\/\//$perforce_checkout\//;
    $line =~ s/#.*//;
    print("$line\n");
}
