#!/usr/bin/perl

my @paths = qw|
    //cj/personal/mroberts/...
    //cj/personal/calbright/...
    //cj/software/...
|;

system("p4 revert -a -c default"); # Revert unchanged files in the default changelist
system("date");
system("p4 sync $_") # sync changes from the important branches
    for @paths;
system("date");
