#!/bin/bash
source $GOCK_HOME

if [ $1 ]; then
    cd $1
else
    gock personal
fi;

echo "Rebuilding tags for $PWD"
ctags --recurse=yes --links=yes --java-types=cimp --exclude='database-dw' --exclude='*.js' --exclude='*Bug*' --exclude='*.as' -f .tags
