.\" Manpage for sup_2.
.\" Contact vivek@nixcraft.net.in to correct errors or typos.
.TH man 8 "06 May 2010" "1.0" "sup_2 man page"
.SH NAME
sup_2 \- create a new LDAP user
.SH SYNOPSIS
sup_2 [USERNAME]
.SH DESCRIPTION
sup_2 is high level shell program for adding users to LDAP server.
On Debian, administrators should usually use sup_2.debian(8) instead.
.SH OPTIONS
The sup_2 does not take any options. However, you can supply
username.
.SH SEE ALSO
useradd(8), passwd(5), sup_2.debian(8)
.SH BUGS
No known bugs.
.SH AUTHOR
Vivek Gite (vivek@nixcraft.net.in)
