#!/bin/bash

echo "Ticket Number"
read ticketNumber
echo "Description"
read description

export STICKIES=$HOME/.stickies

fileName=$STICKIES/$ticketNumber
echo

PAD_STATIC_URL="http://chelhdpdev003.karmalab.net:3001/p"
STATIC_URL="https://jira/jira/browse/EDW"
PAD_NAME=""
PAD_LINK_NAME=""

if [[ $ticketNumber > 80000 ]]; then
  STATIC_URL+='-'
  PAD_NAME="qa-$ticketNumber"
  PAD_LINK_NAME="QA STEPS"
else
  STATIC_URL+='X-'
  PAD_NAME="${ticketNumber}_tasknotes"
  PAD_LINK_NAME="TASKNOTES"
fi

echo "<a href=\"$STATIC_URL$ticketNumber\">$ticketNumber</a><br>$description<hr>" | tee $fileName
echo "<a href=\"$PAD_STATIC_URL/$PAD_NAME\">$PAD_LINK_NAME</a><br>" | tee -a $fileName
