#!/usr/bin/env perl
use strict;
use warnings;

$START=$ARGV[0]
$END=$ARGV[1]

while (<>) {
  if (/$START/../$END/) {
    #next if /START/ || /END/; use this if you DON"T want to include start / end
    print;
  }
}
