#!/bin/bash

snap-back initdb-all
wait $!
dbstart
countOutLoud 7
setDate
wait $!
countOutLoud 3
wait $!
compile-schemas $1
if [[ $? != 0 ]]; then
    echo compile schemas failed
    exit 1    
fi
roll-partitions
