#!/bin/bash

secondsToWait=$1

#snap-back initdb-all
snap-back nopasswd
wait $!
echo starting devdb
dbstart
countOutLoud ${secondsToWait:-7}
echo setting devdb date to local box date
setDate
wait $!
countOutLoud 3
wait $!
echo changing dir to home directory
cd $HOME
compile-schemas $1
if [[ $? != 0 ]]; then
    echo compile schemas failed
    exit 1    
fi
roll-partitions
