#!/bin/bash

echo "
    def setManualBreakPoint = {                  // <-- setting manual breakpoint here
        Runtime run = Runtime.getRuntime()       // <--
        Process pr = run.exec(\"xterm\")           // <--
        pr.waitFor()                             // <--
    }                                            // <-- setting manual breakpoint here

    setManualBreakPoint()                        // <-- setting manual breakpoint here
"
