#!/bin/bash

source $FUNCTIONS/allow-ssh.func
USER=${ALT_USER:-$USER}


CURRENT_CONNECTION=$HOME/.current_server
[[ ! -s $CURRENT_CONNECTION ]] && echo "chsxedwhdc002.idx.expedmz.com" > $CURRENT_CONNECTION

function set_connection {
    CONNECTION=$(cat $CURRENT_CONNECTION)
}

if [[ $# == 2 ]]; then
    echo $1 > $CURRENT_CONNECTION
fi

set_connection

allow-ssh

#while getopts "s" opt; do
#
#    case $opt in 
#        s)
#            echo $CONNECTION
#            ;;
#        \?)
#           echo "Invalid option: -$OPTARG" >&2
#           ;;
#        :)
#           ;;
#    esac
#done
LOCATION=${PWD}


if [[ $# == 0 ]]; then #just connect
    ssh $USER@$CONNECTION
else #pass commands
    ssh -t $CONNECTION "cd $LOCATION; $@"
fi
